# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_locationmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('description', models.TextField(db_column='description')),
                ('buyer_id', models.ForeignKey(db_column='buyer_id', on_delete=django.db.models.deletion.CASCADE, to='api.BuyerModel')),
                ('item_id', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, to='api.ItemModel')),
            ],
        ),
        migrations.AlterField(
            model_name='ratingmodel',
            name='review',
            field=models.TextField(db_column='review'),
        ),
    ]
