# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170206_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyermodel',
            name='address_id',
            field=models.OneToOneField(db_column='address_id', on_delete=django.db.models.deletion.PROTECT, to='api.AddressModel'),
        ),
        migrations.AlterField(
            model_name='buyermodel',
            name='billing_id',
            field=models.OneToOneField(db_column='billing_id', on_delete=django.db.models.deletion.PROTECT, to='api.BillingModel'),
        ),
        migrations.AlterField(
            model_name='buyermodel',
            name='password_id',
            field=models.OneToOneField(db_column='password_id', on_delete=django.db.models.deletion.PROTECT, to='api.PasswordModel'),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='address_id',
            field=models.OneToOneField(db_column='address_id', on_delete=django.db.models.deletion.PROTECT, to='api.AddressModel'),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='billing_id',
            field=models.OneToOneField(db_column='billing_id', on_delete=django.db.models.deletion.PROTECT, to='api.BillingModel'),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='password_id',
            field=models.OneToOneField(db_column='password_id', on_delete=django.db.models.deletion.PROTECT, to='api.PasswordModel'),
        ),
        migrations.AlterField(
            model_name='sellermodel',
            name='address_id',
            field=models.OneToOneField(db_column='address_id', on_delete=django.db.models.deletion.PROTECT, to='api.AddressModel'),
        ),
        migrations.AlterField(
            model_name='sellermodel',
            name='billing_id',
            field=models.OneToOneField(db_column='billing_id', on_delete=django.db.models.deletion.PROTECT, to='api.BillingModel'),
        ),
        migrations.AlterField(
            model_name='sellermodel',
            name='password_id',
            field=models.OneToOneField(db_column='password_id', on_delete=django.db.models.deletion.PROTECT, to='api.PasswordModel'),
        ),
    ]
