# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170219_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billingmodel',
            name='card_expiry',
            field=models.DateField(db_column='card_expiry'),
        ),
    ]
