# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170224_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationmodel',
            name='seller_id',
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='search_id',
            field=models.ForeignKey(db_column='search_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.SearchModel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchmodel',
            name='latitude',
            field=models.FloatField(db_column='latitude', default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchmodel',
            name='longitude',
            field=models.FloatField(db_column='longitude', default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchmodel',
            name='radius',
            field=models.IntegerField(db_column='radius', default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buyermodel',
            name='profile_pic',
            field=models.URLField(db_column='profile_pic', default=None, max_length=1024, null=True),
        ),
        migrations.DeleteModel(
            name='LocationModel',
        ),
    ]
